# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20170211_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='card',
            name='subtypes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='types',
        ),
        migrations.AddField(
            model_name='cardsubtypes',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CardSubtype', to='cards.Card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardtype',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CardType', to='cards.Card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CardColor', to='cards.Card'),
            preserve_default=False,
        ),
    ]
