# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20170226_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(max_length=50),
        ),
    ]
